###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: warn
server:
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

access_control:
  default_policy: deny
  rules:
    - domain: auth.centip3.de
      policy: bypass
    - domain:
        - "code.centip3.de"
        - "traefik.centip3.de"
        - "radarr.centip3.de"
        - "sabnzb.centip3.de"
      policy: two_factor

        #session:
  # expiration: 3600 # 1 hour
  # inactivity: 300 # 5 minutes
  # domain: centip3.de # Should match whatever your root protected domain is
session:
  name: authelia_session
  cookies:
    - domain: 'centip3.de'
      authelia_url: 'https://auth.centip3.de'
      default_redirection_url: 'https://www.centip3.de'
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  mysql:
    host: 192.168.90.250
    port: 3306
    database: authelia
    username: authelia
      #  local:
      #    path: /config/db.sqlite3

notifier:
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  smtp:
    address: 'smtp://smtp.sendgrid.net:587'
    sender: 'authelia@centip3.de'
    username: apikey
      #  filesystem:
      #    filename: /config/notification.txt  #
